Job-Plataform/Models/JobPost.cs
using System;

namespace Job_Plataform.Models
{
    public class JobPost
    {
        public int Id { get; set; }
        public string JobTitle { get; set; }
        public string JobLocation { get; set; }
        public string Description { get; set; }
        public int Salary { get; set; }
        public DateTime StartDate { get; set; }
        public string CompanyName { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public string ContactWebSite { get; set; }
        public byte[] CompanyImage { get; set; }
        public string OwnerUserName { get; set; }

    }
}

Job-Plataform/Controllers/JobPostController.cs
using Job_Plataform.Data;
using Job_Plataform.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using System.Linq;

namespace Job_Plataform.Controllers
{
    [Authorize]
    public class JobPostController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        public JobPostController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        public IActionResult Index()
        {
            if(User.IsInRole("Admin"))
            {
                var allPosts = _dbContext.JobPosts.ToList();
                return View(allPosts);
            }

            var jobFromDb = _dbContext.JobPosts.Where(_ => _.OwnerUserName == User.Identity.Name).ToList();
            return View(jobFromDb);
        }
        public IActionResult UpsertJobPost(int id)
        {
            if(id != 0)
            {
                var jobFromDb = _dbContext.JobPosts.SingleOrDefault(_ => _.Id == id);

                if(jobFromDb.OwnerUserName != User.Identity.Name && !User.IsInRole("Admin"))
                    return Unauthorized();

                if(jobFromDb != null)
                {
                    return View(jobFromDb);
                }
                else
                {
                    return NotFound();
                }
                
            }

            return View();
        }
        public IActionResult UpsertJobForm(JobPost job, IFormFile fileForImage)
        {
            job.OwnerUserName = User.Identity.Name;

            if(fileForImage != null)
            {
                using(var ms = new MemoryStream())
                {
                    fileForImage.CopyTo(ms);
                    var bytes = ms.ToArray();
                    job.CompanyImage = bytes;
                }
            }

            if(job.Id == 0)
            {
                _dbContext.JobPosts.Add(job);
            }
            else
            {
                var jobFromDb = _dbContext.JobPosts
                    .SingleOrDefault(_ => _.Id == job.Id);

                if(jobFromDb == null)
                {
                    return NotFound();
                }

                jobFromDb.JobTitle = job.JobTitle;
                jobFromDb.JobLocation = job.JobLocation;
                jobFromDb.Description = job.Description;
                jobFromDb.Salary = job.Salary;
                jobFromDb.StartDate = job.StartDate;
                jobFromDb.CompanyName = job.CompanyName;
                jobFromDb.ContactPhone = job.ContactPhone;
                jobFromDb.ContactEmail = job.ContactEmail;
                jobFromDb.ContactWebSite = job.ContactWebSite;
                jobFromDb.CompanyImage = job.CompanyImage;                
            }

            _dbContext.SaveChanges();

            return RedirectToAction("Index");
        }
        [HttpDelete]
        public IActionResult DeleteJobPostById(int id)
        {
            if(id == 0)
                return BadRequest();

            var jobFromDb = _dbContext.JobPosts.SingleOrDefault(_ => _.Id == id);

            if( jobFromDb == null)
                return NotFound();

            _dbContext.JobPosts.Remove(jobFromDb);
            _dbContext.SaveChanges();

            return Ok();
        }
    }
}

Job-Plataform/Views/JobPost/CreateEditJobPost.cshtml
@model JobPost
@{
    ViewData["Title"] = "Create or Edit";
}



<form asp-controller="JobPost" asp-action="CreateEditJobForm" enctype="multipart/form-data">

    <div class="card">
        <div class="card-header">
            <h5>Inserat bearbeiten</h5>
        </div>
        <div class="card-body">
            <input hidden asp-for="Id"/>
            <div class="row">
                <div class="col form-group">
                    <input class="form-control" asp-for="JobTitle" type="text" placeholder="Bitte trage eine Jobbezeichnung ein" />
                </div>
                <div class="col">
                    <input class="form-control" asp-for="JobLocation" type="text" placeholder="Bitte trage einen Ort ein" />
                </div>
            </div>

            <div class="row form-group">
                <div class="col form-group">
                    <textarea rows="6" class="form-control" asp-for="Description" placeholder="Bitte trage eine ausfürliche Beschreibung ein"></textarea>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-4">
                    <input class="form-control" asp-for="Salary" type="number" placeholder="Wie viel Jahresgehalt zahlst ihr?" />
                </div>
            </div>

            <div class="row form-group">
                <div class="col-3">
                    <div class="col-form-label">
                        Wann startet der Job?
                    </div>
                    <input class="form-control" asp-for="StartDate" type="date" />
                </div>
            </div>

            <hr/>

            <div class="row form-group">
                <div class="col">
                    <input class="form-control" asp-for="CompanyName" type="text" placeholder="company name" />
                </div>
                <div class="col">
                    <input class="form-control" asp-for="ContactWebSite" type="url" placeholder="website address" />
                </div>
            </div>

            <div class="row form-group">
                <div class="col">
                    <input class="form-control" asp-for="ContactPhone" type="tel" placeholder="phone number"/>
                </div>
                <div class="col">
                    <input class="form-control" asp-for="ContactEmail" type="email" placeholder="email"/>
                </div>
            </div>

            <div class="row form-group">
                <div class="col">
                    <label>Bild</label>
                    <input class="form-control-file" name="fileForImage" type="file"/>
                </div>
            </div>

        </div>
        <div class="card-footer">
            <button class="btn btn-primary" type="submit">Speichern</button>
        </div>
    </div>

</form>

Job-Plataform/Views/JobPost/Index.cshtml
@model List<JobPost>
@{
    ViewData["Title"] = "Your Ads";
}
<a class="btn btn-primary" asp-controller="JobPost" asp-action="CreateEditJobPost">Publish a new ad</a>

<table id="jobPostTable" class="table table-bordered table-striped table-hover">
    <thead class="thead-dark">
        <tr>
            <th>Job Title</th>
            <th>Ort</th>
            <th>Firma Name</th>
            <th>Aktionen</th>
        </tr>

    </thead>
    <tbody>
        @{
            foreach (JobPost job in Model)
            {
                <tr>
                    <td>@job.JobTitle</td>
                    <td>@job.JobLocation</td>
                    <td>@job.CompanyName</td>
                    <td>
                        <a asp-route-id="@job.Id" class="btn btn-warning" asp-controller="JobPost" asp-action="UpsertJobPost">Edit</a>
                        <button class="btn btn-danger" onclick="onClickDelete(@job.Id)">Delete</button>
                    </td>
                </tr>
            }
        }

    </tbody>
</table>

@section Scripts{
<script>

              $(document).ready( function () {
              $('#jobPostTable').DataTable();
          } );

          function onClickDelete(id){
              Swal.fire({
        title: 'Do you want to delete this post?',
        icon: 'warning',
        showCloseButton: true,
        showCancelButton: true,
        focusConfirm: false,
        confirmButtonText: 'Yes, delete it!',
        confirmButtonAriaLabel: 'Thumbs up, great!',
      }).then((result) => {
            if (result.isConfirmed)
            {
                $.ajax({
                    type: "DELETE",
                    url:"@Url.Action("DeleteJobPostById")",
                    data:{id: id},
                    success: function(msg){                      
                        Swal.fire('Wurde gelöscht!', '','success')
                        .then((result) =>{
                            location.reload();
                        });
                    },
                    error: function(msg){
                        Swal.fire('Ops!, etwas ist shief gelaufen!', '','error')
                    }
                });
            }
      })
    }

</script>
}

Job-Plataform/Views/JobPost/UpsertJobPost.cshtml
@model JobPost
@{
    ViewData["Title"] = "Create or Edit";
}

<form asp-controller="JobPost" asp-action="UpsertJobForm" enctype="multipart/form-data">

    <div class="card">
        <div class="card-header">
            <h5>Edit Ad</h5>
        </div>
        <div class="card-body">
            <input hidden asp-for="Id"/>
            <div class="row">
                <div class="col form-group">
                    <input class="form-control" asp-for="JobTitle" type="text" placeholder="Bitte trage eine Jobbezeichnung ein" />
                </div>
                <div class="col">
                    <input class="form-control" asp-for="JobLocation" type="text" placeholder="Bitte trage einen Ort ein" />
                </div>
            </div>

            <div class="row form-group">
                <div class="col form-group">
                    <textarea rows="6" class="form-control" asp-for="Description" placeholder="Bitte trage eine ausfürliche Beschreibung ein"></textarea>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-4">
                    <input class="form-control" asp-for="Salary" type="number" placeholder="Wie viel Jahresgehalt zahlst ihr?" />
                </div>
            </div>

            <div class="row form-group">
                <div class="col-3">
                    <div class="col-form-label">
                        Wann startet der Job?
                    </div>
                    <input class="form-control" asp-for="StartDate" type="date" />
                </div>
            </div>

            <hr/>

            <div class="row form-group">
                <div class="col">
                    <input class="form-control" asp-for="CompanyName" type="text" placeholder="company name" />
                </div>
                <div class="col">
                    <input class="form-control" asp-for="ContactWebSite" type="url" placeholder="website address" />
                </div>
            </div>

            <div class="row form-group">
                <div class="col">
                    <input class="form-control" asp-for="ContactPhone" type="tel" placeholder="phone number"/>
                </div>
                <div class="col">
                    <input class="form-control" asp-for="ContactEmail" type="email" placeholder="email"/>
                </div>
            </div>

            <div class="row form-group">
                <div class="col">
                    <label>Bild</label>
                    <input class="form-control-file" name="fileForImage" type="file"/>
                </div>
            </div>

        </div>
        <div class="card-footer">
            <button class="btn btn-primary" type="submit">Save</button>
        </div>
    </div>

</form>